### ISSUE TITLE
Missing instructions for building in Linux

### ISSUE THREAD

**Issue by johnblommers** [gue-ni/OpenGL_Flightsim#3]
From what I can gather this project will only work on Windows since it requires Microsoft Visual Studio to build it.

Can you suggest the way to compile this software on Debian-based Linux distros please? Even a simple `Makefile`  would be welcome.

**Comment by muddessir** [comment]
_(even though it's not working)_

[meson.build.txt](https://github.com/gue-ni/OpenGL_Flightsim/files/10731473/meson.build.txt)
[patch.patch.txt](https://github.com/gue-ni/OpenGL_Flightsim/files/10731489/patch.patch.txt)

**Comment by yangosoft** [comment]
https://github.com/gue-ni/OpenGL_Flightsim/pull/7 try this pull request

**Comment by gue-ni** [comment]
build instructions and cmake file have been added
