### ISSUE TITLE
Instructions for building on windows

### ISSUE THREAD

**Issue by MacP47** [gue-ni/OpenGL_Flightsim#4]
Any chance you could update what is required to build this on windows?

Attempting to build with visual studio and getting a plethora of reference errors.. Thanks!

**Comment by gue-ni** [comment]
I added some instructions, hope this helps. Let me know if something is unclear.

**Comment by johnblommers** [comment]
If I don't apply the patch.patch file and include the meson.build file then I see an ``a.out`` file but running it does nothing, no output, just a return to the shell prompt.

**Comment by gue-ni** [comment]
@johnblommers you are talking about linux, the instructions are for windows

**Comment by johnblommers** [comment]
Yes I'm on Linux with hopes to try your flight sim one day soon. For now let me stand down and observe developments.

**Comment by MacP47** [comment]
Got it working on windows - thank you for the instructions!
